name: Deploy Frontend

on:
    #workflow dispatch allows us to manually trigger a workflow run
  workflow_dispatch:

  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Build
        env:
            VITE_API_BASE: ${{ secrets.VITE_API_URL }}
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: prod-deployment
